# Site settings
title: Daniel Straub
email: daniel.straub@uj.edu.pl
description: > # this means to ignore newlines until "baseurl:"
  Department of Regional Development, Institute of Geography and Spatial Management, Faculty of Geography and Geology, Jagiellonian University, ul. Gronostajowa 7, 30-387 Cracow
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

#twitter_username: straubd_me
#github_username:  jekyll
#orcid_id: 0000-0003-1084-1260

# Google Analytics
google_analytics: UA-152964532-1

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:categories/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""