# Site settings
title: Daniel Straub
email: d.straub@doctoral.uj.edu.pl
description: > # this means to ignore newlines until "baseurl:"
  Socio-economic Geography and Spatial Planning,
  Doctoral School in Social Sciences,
  Jagiellonian University,
  Łojasiewicza 4, 30-348 Cracow
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

#twitter_username: jekyllrb
#github_username:  jekyll
#orcid_id: 0000-0003-1084-1260

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:categories/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""